#!/usr/bin/env bash
# analyze-patterns.sh
# Scans .claude/debugging_log.md for recurring error patterns and skill gaps.
# Writes actionable items to .claude/pending-improvements.md.
# Also runs the skill smoke test and appends any trigger failures.
# Called by session-end.sh after each session.

set -uo pipefail

PROJECT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
LOG_FILE="$PROJECT_DIR/.claude/debugging_log.md"
ERRORS_TMP="$PROJECT_DIR/.claude/session_errors.tmp"
PENDING_FILE="$PROJECT_DIR/.claude/pending-improvements.md"
SMOKE_SCRIPT="$PROJECT_DIR/scripts/implicit-skill-smoke-test.sh"
CONFIG_FILE="$PROJECT_DIR/.claude/config"

# ─── Load config ──────────────────────────────────────────────────────────────
PATTERN_ERROR_CODE_MIN=2
PATTERN_FILE_ERROR_MIN=3
SKILL_GAP_ESCALATE_MIN=2
SMOKE_FAIL_NOTIFY_PRIORITY=high
[[ -f "$CONFIG_FILE" ]] && source "$CONFIG_FILE"

mkdir -p "$PROJECT_DIR/.claude"

FOUND_ITEMS=false
NOW="$(date -u +%Y-%m-%d)"

# ─── 1. Error code frequency ──────────────────────────────────────────────────
declare -A ERROR_COUNTS=()
if [[ -f "$LOG_FILE" ]]; then
  while IFS= read -r code; do
    [[ -z "$code" ]] && continue
    ERROR_COUNTS["$code"]=$(( ${ERROR_COUNTS[$code]:-0} + 1 ))
  done < <(awk -F': ' '/^ERROR_CODE: / {print $2}' "$LOG_FILE" 2>/dev/null | sort || true)
fi

if [[ -f "$ERRORS_TMP" ]]; then
  while IFS= read -r code; do
    [[ -z "$code" ]] && continue
    ERROR_COUNTS["$code"]=$(( ${ERROR_COUNTS[$code]:-0} + 1 ))
  done < <(awk -F': ' '/^ERROR_CODE: / {print $2}' "$ERRORS_TMP" 2>/dev/null | sort || true)
fi

# ─── 2. Hot file detection ────────────────────────────────────────────────────
declare -A FILE_COUNTS=()
if [[ -f "$LOG_FILE" ]]; then
  while IFS= read -r fname; do
    [[ -z "$fname" ]] && continue
    FILE_COUNTS["$fname"]=$(( ${FILE_COUNTS[$fname]:-0} + 1 ))
  done < <(grep -oE '[a-zA-Z0-9_/-]+\.[a-zA-Z0-9]{1,6}' "$LOG_FILE" 2>/dev/null | sort || true)
fi

# ─── 3. Skill gap detection from structured Debug Entry blocks ────────────────
declare -A SKILL_GAP_COUNTS=()
declare -A SKILL_GAP_SAMPLES=()
if [[ -f "$LOG_FILE" ]]; then
  while IFS= read -r line; do
    if [[ "$line" =~ \*\*Skill\ gap:\*\* ]]; then
      gap_text=$(echo "$line" | sed 's/\*\*Skill gap:\*\*[[:space:]]*//')
      skill_name=$(echo "$gap_text" | grep -oE '[a-z]+-[a-z][a-z-]+[a-z]' | head -1 || true)
      if [[ -n "$skill_name" ]]; then
        SKILL_GAP_COUNTS["$skill_name"]=$(( ${SKILL_GAP_COUNTS[$skill_name]:-0} + 1 ))
        SKILL_GAP_SAMPLES["$skill_name"]="${gap_text:0:120}"
      fi
    fi
  done < "$LOG_FILE"
fi

# ─── 4. Run skill smoke test ──────────────────────────────────────────────────
SMOKE_OUTPUT=""
SMOKE_FAILURES=0
if [[ -x "$SMOKE_SCRIPT" ]]; then
  SMOKE_OUTPUT=$(bash "$SMOKE_SCRIPT" --report 2>&1 || true)
  SMOKE_FAILURES=$(echo "$SMOKE_OUTPUT" | grep -c '^❌' || true)
fi

# ─── 5. Build findings ────────────────────────────────────────────────────────
RECURRING_ERRORS=""
for code in "${!ERROR_COUNTS[@]}"; do
  [[ ${ERROR_COUNTS[$code]} -ge ${PATTERN_ERROR_CODE_MIN:-2} ]] && {
    RECURRING_ERRORS="$RECURRING_ERRORS\n- **$code** — ${ERROR_COUNTS[$code]}x in log"
    FOUND_ITEMS=true
  }
done

RECURRING_FILES=""
for fname in "${!FILE_COUNTS[@]}"; do
  [[ ${FILE_COUNTS[$fname]} -ge $PATTERN_FILE_ERROR_MIN ]] && {
    RECURRING_FILES="$RECURRING_FILES\n- \`$fname\` — ${FILE_COUNTS[$fname]}x"
    FOUND_ITEMS=true
  }
done

SKILL_GAP_ITEMS=""
ESCALATED_SKILLS=""
for skill in "${!SKILL_GAP_COUNTS[@]}"; do
  count=${SKILL_GAP_COUNTS[$skill]}
  sample="${SKILL_GAP_SAMPLES[$skill]:-}"
  SKILL_GAP_ITEMS="$SKILL_GAP_ITEMS\n- **$skill** — $count gap mention(s): _${sample}_"
  FOUND_ITEMS=true
  [[ $count -ge $SKILL_GAP_ESCALATE_MIN ]] && ESCALATED_SKILLS="$ESCALATED_SKILLS $skill($count)"
done

[[ $SMOKE_FAILURES -gt 0 ]] && FOUND_ITEMS=true

if ! $FOUND_ITEMS; then
  echo "✅ PATTERNS: No recurring patterns or skill gaps detected"
  exit 0
fi

# ─── 6. Write to pending-improvements.md ─────────────────────────────────────
{
  echo ""
  echo "---"
  echo "## Pending Improvements — $NOW"
  echo ""
  echo "> Auto-generated by \`scripts/analyze-patterns.sh\`."
  echo "> **Review at session start before any other work.**"
  echo ""

  if [[ -n "$RECURRING_ERRORS" ]]; then
    echo "### Recurring Error Codes"
    echo -e "$RECURRING_ERRORS"
    echo ""
    echo "**Action:** Look up each error code in \`.claude/debugging_log.md\`."
    echo "If caused by the same logical mistake, append to \`memory/debugging_patterns.md\`"
    echo "and update the relevant skill's body guidance with a prevention rule."
    echo ""
  fi

  if [[ -n "$RECURRING_FILES" ]]; then
    echo "### Hot Files (repeated error locations)"
    echo -e "$RECURRING_FILES"
    echo ""
    echo "**Action:** These files generate repeated errors. Review active skills for their"
    echo "domain and ensure edge cases being missed are covered in 'When to Use' or body."
    echo ""
  fi

  if [[ -n "$SKILL_GAP_ITEMS" ]]; then
    echo "### Skill Gap Mentions (from Debug Entries)"
    echo -e "$SKILL_GAP_ITEMS"
    echo ""
    if [[ -n "$ESCALATED_SKILLS" ]]; then
      echo "⚠️  **ESCALATED (≥${SKILL_GAP_ESCALATE_MIN}x):$ESCALATED_SKILLS**"
      echo ""
    fi
    echo "**Action:** Run \`skill-improvement-loop\` for each listed skill:"
    echo "1. Score with the 0–2 rubric (trigger quality, scope fit, outcome support, noise)"
    echo "2. Rewrite description + 'When to Use' if score < 7/8"
    echo "3. Update \`SKILL_MAP.md\` if scope changed; update \`CLAUDE.md\` if triggering domain changed"
    echo "4. Re-run \`bash scripts/implicit-skill-smoke-test.sh\` — must reach all passing"
    echo "5. Update \`memory/skill_effectiveness.md\` with new score"
    echo ""
  fi

  if [[ $SMOKE_FAILURES -gt 0 ]]; then
    echo "### Skill Smoke Test Failures ($SMOKE_FAILURES)"
    echo '```'
    echo "$SMOKE_OUTPUT" | grep -A5 '^❌' | head -60
    echo '```'
    echo ""
    echo "**Action:** Same as skill gap procedure above — fix descriptions, re-run smoke test."
    echo ""
  fi

  echo "---"
  echo ""
} >> "$PENDING_FILE"

# ─── 7. Notify ────────────────────────────────────────────────────────────────
SUMMARY=""
[[ -n "$RECURRING_ERRORS" ]] && SUMMARY="Recurring error codes. "
[[ -n "$SKILL_GAP_ITEMS" ]] && SUMMARY="${SUMMARY}Skill gaps detected. "
[[ $SMOKE_FAILURES -gt 0 ]] && SUMMARY="${SUMMARY}${SMOKE_FAILURES} smoke test failure(s)."

if [[ -n "$ESCALATED_SKILLS" ]]; then
  PRIORITY="${SKILL_GAP_NOTIFY_PRIORITY:-urgent}"
  MSG="🚨 URGENT skill gap(s) escalated:$ESCALATED_SKILLS — fix before next session"
else
  PRIORITY="${SMOKE_FAIL_NOTIFY_PRIORITY:-high}"
  MSG="Improvements pending: ${SUMMARY}Check .claude/pending-improvements.md"
fi

bash "$PROJECT_DIR/scripts/notify.sh" \
  "$MSG" "Claude Code — Action Needed" "$PRIORITY" "wrench,claude" 2>/dev/null || true

echo "⚠️  PATTERNS: Items written to .claude/pending-improvements.md"
